### ISSUE TITLE
Add and play via JSON-RPC doesn't work

### ISSUE THREAD

**Issue by khloke** [skipmodea1/plugin.video.dumpert#1]
Hi,

I've been trying to make my Chrome extension play-to-kodi work with your add-on, but with no success.

I did a POST with the following JSON:
`POST [{"jsonrpc": "2.0", "method": "Playlist.Add", "params":{"playlistid":1, "item" :{ "file" : "plugin://plugin.video.dumpert/?action=play&video_page_url=http%3A%2F%2Fwww.…rt.nl%2Fmediabase%2F6720753%2F9b539809%2Fjatbontkraagje_in_de_vistent.html" }}, "id" :1}]`
then a 
`POST {"jsonrpc": "2.0", "method": "Player.Open", "params":{"item":{"playlistid":1, "position" : 0}}, "id": 1}`

It looks like the add-on would try to find and play the given video, but fails immediately.

Can you look into it?

Cheers,
KH

**Comment by skipmodea1** [comment]
Hija,

I don't know much about JSON stuff unfortunately.

However the addon has a debug switch, i suggest turning it on and seeing 
what error appears in the kodi log file. Maybe that can give you a clue 
what's going wrong...

Good luck

Skipmode A1

On 3-2-2016 13:52, Khee-Hong Loke wrote:

> Hi,
> 
> I've been trying to make my Chrome extension play-to-kodi work with 
> your add-on, but with no success.
> 
> I did a POST with the following JSON:
> |POST [{"jsonrpc": "2.0", "method": "Playlist.Add", 
> "params":{"playlistid":1, "item" :{ "file" : 
> "plugin://plugin.video.dumpert/?action=play&video_page_url=http%3A%2F%2Fwww.…rt.nl%2Fmediabase%2F6720753%2F9b539809%2Fjatbontkraagje_in_de_vistent.html" 
> }}, "id" :1}]|
> then a
> |POST {"jsonrpc": "2.0", "method": "Player.Open", 
> "params":{"item":{"playlistid":1, "position" : 0}}, "id": 1}|
> 
> It looks like the add-on would try to find and play the given video, 
> but fails immediately.
> 
> Can you look into it?
> 
> Cheers,
> KH
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/skipmodea1/plugin.video.dumpert/issues/1.

---

Dit e-mailbericht is gecontroleerd op virussen met Avast antivirussoftware.
https://www.avast.com/antivirus
